### ISSUE TITLE
Incorrect typing

### ISSUE THREAD

**Issue by loreanvictor** [staltz/callbag-share#11]
I might be mistaken here, but is [this](https://github.com/staltz/callbag-share/blob/d05dff4ef6023deba5008f4377dec4fca5b9cfb2/types.d.ts#L3) typing correct? Assume I have type `T` extending `Source` like this:
```ts
type Extension<T> = Source<T> & { message: string }
```

According to current type definition, if `e` is `Extension<T>`, then `share(e)` is also `Extension<T>`, which means `share(e).message` would always be a string, which is not a case (the returned function by `share()` never has a property name `message`).

[playground](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcDKAVAggJQ3AXjgAYBuAKFElgWVQBEttC4BGCq6eJFOAUQBy9FgCYO4LrV44+aPjgBqfegH0AzCzXjq3OnBlzFylQBYWJ7ZJ6oD8paoCsLB5ZrX9su8YBsLb691pTyNVAHYWUICpG2D7FQAOFnio91sQlQBOFgyKcgB6ACoC8jgCuCw4AGEAQwAbWoAjaoBzOAATRAA7aoBbAEsAYzraxDgoYAHgPoA3YABnOD7OsABXeAgAM2i4AEkSsurOtvau3sHh0bbgWpngKAWINdX1rfcAeX28ygkaJZg7jbVSZVYZNZoAHh2ABo4G8AHxwADeJTgAAoYAAudDYPAwtpYmr1MHgt4wnZwgCUWOmED6bQocDRmLgjGweKxOypcBpdIZTKxgnoeIA-FjDoguTz6eQAL7kfJFfblOBzR5QYEQTojdrXW73drVGDVT7fHSLTr-KCA4FoNWTcEYBGgf5HBaExotcGdYCzKAwx1IuXkK4DWrVcZwDYrToDGB9TUqgAW4eADrgzuArvQdtT4rhcNRqpW6uAWIwXIwuU4bj0fBALrm8c6DoRRFtxftAYAZEi4D15nMWqWVTAoEtWjKKCGwxGBpq5vBh3WG02vSseg07nDcnk8nAALT7hEwRN9BZzROPWrHZOzOCHdNQKDQGGNmOoC8p1EUxYLToQeBxhgYtOnHe9OjgAADZdM0bTVIIAOnIOdOgXdMRAFetYNXTp103KBWyTL9gApCggA)

**Comment by staltz** [comment]
Share returns T where T extends Source, so I believe it is correct. Have you tried interface instead of type?

**Comment by loreanvictor** [comment]
@staltz [yes](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcDKAVAggJQ3AXjgAYBuAKFElgWVQBEttC4BGCq6eJFOAUQBy9FgCYO4LrV44+aPjgBqfegH0AzCzXjq3OnBlzFylQBYWJ7ZJ6oD8paoCsLB5ZrX9su8YBsLb691pTyNVAHYWUICpG2D7FQAOFnio91sQlQBOFgyKcgB6ACoC8jgCuCw4AGEAQwAbWoAjaoBzOAATRAA7aoBbAEsAYzraxDgoYAHgPoA3YABnOD7OsABXeAgAM2i4AEkSsurOtvau3sHh0bbgWpngKAWINdX1rfcAeX28ygkaJZg7jbVSZVYZNZoAHh2ABo4G8AHxwADeJTgAAoYAAudDYPAwtpYmr1MHgt4wnZwgCUWOmED6bQocDRmLgjGweKxOypcBpdIZTKxgnoeIA-FjDoguTz6eQAL7kfJFfblOBzR5QYEQTojdrXW73drVGDVT7fHSLTr-KCA4FoNWTcEYBGgf5HBaExotcGdYCzKAwx1IuXkK4DWrVcZwDYrToDGB9TUqgAW4eADrgzuArvQdtT4rhcNRqpW6uAWIwXIwuU4vwtAKBqD4IBdc3jnQdTqbmbaC1txftAcRcB68zmLVLKpgUCWrRlFBDYYjA01c3g48bzdbXpWPQadzhuTyeTgAFpjwiYIm+gsr9FjtUFiup51mjCGmtFvAb9GrhslsBjksYzAHUfRIOQczJuMqLABSAB0w5zKOzTABQQA). still the same issue remains.

The reason is that `share()` does NOT return `T` where `T extends Source<Z>`. It simply returns `Source<Z>` (and not the extended type `T`). Perhaps this example illuminates what I mean in a more clear way:

```ts
import { Source } from 'callbag'
import of from 'callbag-of'
import share from 'callbag-share'


interface Extended<T> extends Source<T> {
  message: string
}

function makeExtended<T>(src: Source<T>): Extended<T> {
  const res: Extended<T> = ((t, d) => src(t, d)) as any
  res.message = 'hellow!'

  return res
}

function logMessage<T>(e: Extended<T>) {
  console.log(e.message.trim())
}

const ext = makeExtended(of(42))
logMessage(ext)

const shared = share(ext)
//
// this must be a compile time error.
// because of the typing, it is now a runtime error.
//
logMessage(shared)
```
[playground](https://stackblitz.com/edit/callbag-share-typing-issue?file=index.ts)

**Comment by staltz** [comment]
Oh, I see. So this issue is fundamentally about runtime behavior, not just types. I don't think it's the purpose of this library to transparently return a proxied object of the input object. `share()` is about returning a callbag source that broadcasts emissions of the input source. 

If you want to access ad-hoc properties of the input source through the output source, I think it's best that you make a new library, based on callbag-share, (perhaps called `callbag-share-with-proxy`) that uses JS `Proxy` with getters and setters to transparently forward property access.

Personally, I would solve this differently. I wouldn't attach any properties to callbags (they are functions after all, properties attached to functions is possible, but weird). I would attach the callbag to an object. Like `{callbag, message}`, and then the `share()` is applied only on `obj.callbag`.

**Comment by loreanvictor** [comment]
Ah yes my point was not to change `share()`'s behavior by any means. The example was only to illustrate that `share()`'s input type is NOT the same as its return type, but current type definition implies it is.

In other words, if the type definition was changed to this:
```ts
import { Source } from 'callbag';

export default function share<T>(source: Source<T>): Source<T>;
```
then in case of provided example the error would become a compilation error and not a runtime error (which is the purpose of typing in general).

**Comment by staltz** [comment]
Yep, I'm open to that change! I think it was @Andarist who originally wrote them, so I'd like to hear from him if possible.

**Comment by Andarist** [comment]
The proposed type is better and what I would write today 😉 So I would say that it's best to just file a PR fixing this.

**Comment by loreanvictor** [comment]
Sure thing, [just did](https://github.com/staltz/callbag-share/pull/12).

**Comment by staltz** [comment]
1.3.0
